### ISSUE TITLE
Pull fixes for facebook/hhvm#7133

### ISSUE THREAD

**Issue by daxtens** [PPC64/hhvm#144]
In https://github.com/facebook/hhvm/issues/7133, upstream makes a fix that improves HHVM performance for some string functions.

**Comment by racardoso** [comment]
That's very nice. We often merge upstream every Thursday. But in this case i will update today because i'm running oss-performance benchmarks. Thanks.

**Comment by racardoso** [comment]
Closed via 9530837  However, i don't see any performance increase or decrease on oss-performance.

**Comment by daxtens** [comment]
Ok, I wasn't sure when you normally merged or if you had a regular schedule
- I'll know for next time.

There doesn't seem to be any performance win on most macrobenchmarks but
there are for microbenchmarks.

Thanks!

**Comment by racardoso** [comment]
@daxtens Np. By the way, as soon as possible, those merges will be made automatically in a daily basis we do this. Now we do this manually that's why we normally do that once a week. But if you saw something upstream that caught your attention please let us know about it and feel free to open tasks like this if you want. Thanks.
