### ISSUE TITLE
Analyse performance gains by tweeking "Default Prefetch Depth" register

### ISSUE THREAD

**Issue by gut** [PPC64/hhvm#145]
System wide changes can be done with the following command on power machines:
`ppc64_cpu --dscr=7` (deepest data prefetch)

The default value for dscr is `0`.

If some gain is detected, then this special register could be written when our JIT is running to take advantage of it.

**Comment by gromero** [comment]
@igorsnunes This is how it looks like on my 16.04 (I know you are using 15.04, but IIRC it's exactly the same package that provides the `ppc64_cpu` tool:

```
~# ppc64_cpu --dscr
DSCR is 0
~# ppc64_cpu --dscr=7
~# ppc64_cpu --dscr
DSCR is 7
~# which ppc64_cpu
/usr/sbin/ppc64_cpu
~# dpkg -S /usr/sbin/ppc64_cpu 
powerpc-ibm-utils: /usr/sbin/ppc64_cpu
~# apt-cache madison powerpc-ibm-utils
powerpc-utils |    1.3.1-2 | http://archive.ubuntu.com/ubuntu xenial/main Sources
```

**Comment by gromero** [comment]
Just for the records. As we discussed, @racardoso suggestion on performing an addittional test w/ and w/o `DSCR=7` but setting *relocation always on* might be useful if the reallocated code size is sufficient huge. IMHO,  it's an interesting - although quite simple - test since we are, in other terms, looking at the effect of an aggressive/non-aggressive pre-fetch on a specific part of the code.

**Comment by brunoalr** [comment]
System wide, it worsened the performance with or without relocation (tested with 2mb and 200mb relocation sized). It would not make sense to apply this change locally since the the code is not being copied in chunks that are huge enough to enable further gains.

**Comment by gut** [comment]
But keep in mind that this might make sense for a specific piece of JIT code. As you said we didn't find it yet, but it doesn't mean will not have one.
