### ISSUE TITLE
Assert failing in "function-entry-helpers-x64.cpp"

### ISSUE THREAD

**Issue by lbianc** [PPC64/hhvm#46]
At line 104 the assert "assert_native_stack_aligned(); TODO PPC64" is failing.

**Comment by lbianc** [comment]
This assert may be related with "translator-asm-helpers.S" at line 170, where a change was made to put the frame pointer value in the rigth register to be received as parameter in the called function.

**Comment by racardoso** [comment]
inline void assert_native_stack_aligned() {
#ifndef _MSC_VER
  assert(reinterpret_cast<uintptr_t>(__builtin_frame_address(0)) % 16 == 0);
#endif
}
— Built-in Function: void \* __builtin_return_address (unsigned int level)

This function returns the return address of the current function, or of one 
of its callers. The level argument is number of frames to scan up the call stack. 
A value of 0 yields the return address of the current function, a value of 1 yields 
the return address of the caller of the current function, and so forth. 
When inlining the expected behavior is that the function returns the address of 
the function that is returned to. To work around this behavior use the noinline function attribute.

The level argument must be a constant integer.

On some machines it may be impossible to determine the return address of any 
function other than the current one; in such cases, or when the top of the stack 
has been reached, this function returns 0 or a random value. In addition, __builtin_frame_address 
may be used to determine if the top of the stack has been reached.

**Comment by lbianc** [comment]
The function is being used to return stack frame address and check if it is aligned.
There was an error in the file "translator-asm-helpers.S", where when saving the r3 register, the stack became unaligned. The solution was add 8bytes to the stack size.
