### ISSUE TITLE
Fix trivial nop removal optimization.

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#95]
HHVM Jit generates a lot's of (useless) nops on POWER which can lead to a performance degradation:

```
26: CGetL2 L:0 
(36) ReqBindJmp<26, FPInv 4, IRSP -1, Flags 0> t1:StkPtr, t0:FramePtr
0x1001d801e50:   42 00 a0 3b     addi r29,0,66
0x1001d801e54:   00 00 00 60     nop 
0x1001d801e58:   00 00 00 60     nop
0x1001d801e5c:   00 00 00 60     nop 
0x1001d801e60:   00 00 00 60     nop 
0x1001d801e64:   10 00 21 38     addi r1,r1,16 
0x1001d801e68:   00 00 00 60     nop
0x1001d801e6c:   00 00 00 60     nop
0x1001d801e70:   00 00 00 60     nop 
0x1001d801e74:   00 00 00 60     nop
0x1001d801e78:   00 00 00 60     nop 
0x1001d801e7c:   00 00 00 60     nop 
```

**Comment by gut** [comment]
watch out! those `nop`s are required if the immediate is patched afterwards. Keep that in mind.

Nop should not have a direct performance degradation:

```
If an implementation performs any type of run-time optimization
related to no-ops, the preferred form is the no-op that will trigger this: nop

For some uses of a no-op instruction, optimizations related to no-ops, 
such as removal from the execution stream, are not desireable. An
extended mnemonic is provided for the executed form of no-op.
This form of no-op will still consume execution resources: xnop
```

the problem is that the cache is used less efficiently.

**Comment by racardoso** [comment]
why nop is required when immediate is patched? this make no sense to me. Nop should not have a performance degradation, but we generate lots of nop. The code generated is clobbered of nops and i don't no why. And why cache is used less efficiently?

**Comment by lbianc** [comment]
There are nops, for example, when loading an immediate (see https://github.com/PPC64/hhvm/blob/next/hphp/ppc64-asm/asm-ppc64.cpp#L765).

The reason is that when emiting a branch instruction, the address need to be loaded and its size is not fixed, so there are more or less instructions depending on that (see the conditions https://github.com/PPC64/hhvm/blob/next/hphp/ppc64-asm/asm-ppc64.cpp#L722).

HHVM emits branch instructions and changes its address when the target code changes, for example when using relocation or emiting a smashable jump. Another case is when HHVM emits a branch before emit the target, i. e., it has no target address and it will be filled later, but at this time, we need to allocate enough space to be able to emit the branch.

See the function patchBctr (https://github.com/PPC64/hhvm/blob/next/hphp/ppc64-asm/asm-ppc64.h#L1985). It receives an address, which is the branch address, and overwrites the instructions for load the immediate and the branch to set or change the branch address. The issue here is that the address can be greater or smaller that the original one, if that happens, there will not be enough space and other instructions will be overwritten or garbage will be left on the memory, respectively.

**Comment by racardoso** [comment]
Ok @lbianc i understand the point, but i still don't get why x64 doesn't emit those. Because we generates lots of `nop`, so the cpu lost many cicles doing nothing and this is bad i guess. In the case of a jump i understand the use of `nops` to align the code but, i don't understand why we need to emit those when loading a immediate. Can you clarify this to us?

**Comment by gut** [comment]
The only `nop` that will consume execution resources (aka cpu cycles) is `xnop`.

X64 doesn't emit those as they can load 64 bits at once, so the bits are available there. On X64 we needed to implement `li64`.

If you are that worried for the moment about big immediates, please consider improving this load by using the global offset table in order to right there the immediates needed so we can load it at once with 1 load instruction. After that the patching mechanism has to be changed in order to patch that area instead of the instruction itself.

**Comment by racardoso** [comment]
Apparently -O3 compilation remove some of those nops via -fdce flags for some reason. Maybe this flags removes the function who generate those nops.

**Comment by racardoso** [comment]
There lots of nops generated by hhvm debug code and they are not generated on Release so i'm closing this.
